[build]
  publish = "public"               # Directory containing your static files
  functions = "netlify/functions"  # Directory for serverless functions

[dev]
  command = "npm start"        # Command to run during development (if needed)
